### ISSUE TITLE
Document the interface

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit-tbdiff#4]
Hi,

I don't really understand the buffer Magit-tbdiff. What about explaining what is displayed? Maybe through an example.

**Comment by kyleam** [comment]
>  What about explaining what is displayed? Maybe through an example.

Thanks for the suggestion.  I'm not sure I could do much better than what is in `man git-range-diff`, particularly the [examples section][0].  Do you think pointing to that in the README and/or commentary would help?

[0]: https://git-scm.com/docs/git-range-diff#_examples

**Comment by DamienCassou** [comment]
I have read the man and the examples section. I felt it was not enough. The fact that the examples section does not have the colors that the text talks about doesn't help.

What about describing a similar example with a screenshot of the buffer? If the example came with the steps to reproduce the setup it would then really be perfect in my opinion.

**Comment by kyleam** [comment]
OK, when I find the time, I'll think more about putting together a short walkthrough.  I'm undecided yet on how tailored I should make it to this extension, given that range-diff output seems to be the main source of confusion.  I'll likely end up including both CLI and magit-tbdiff invocations and screenshots.

**Comment by tarsius** [comment]
@kyleam I just went through all the Magit repositories to see whether there are any we forgot about. Not sure if you *forgot* about this, but I figure a friendly ping cannot hurt.

**Comment by kyleam** [comment]
@tarsius Thanks for the ping. 

I notice this time to time in my periodic local todo review.  But at this point, it's clear that I'm not going to actually prioritize doing this, so I'll close this rather than let it linger.  Very little if anything here is specific to this extension.  If somebody does have concrete ideas about how to present a introduction or tutorial on range-diff, I'd be happy to link to it (and review it, if desired), but I don't think it should live in this repo.

**Comment by tarsius** [comment]
:smile:
